#spring:
#  application:
#    name: batch-sample
#  datasource:
#    hikari:
#      maximum-pool-size: 10
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
#  batch:
#    jdbc:
#      initialize-schema: always

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  batch:
    job:
      name: JDBC_BATCH_WRITER_CHUNK_JOB
    jdbc:
      initialize-schema: always